import Head from "next/head";
import data from "../data/staticData.json"
import MainAuth from "../components/sections/mainAuth.jsx/mainAuth";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AO Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <MainAuth data={data} />
    </div>
  );
}
