import Head from "next/head";
import data from "../data/staticData.json";
import MainAuth from "../components/sections/mainAuth.jsx/mainAuth";
import Selector from "../components/sections/selector/selector";
import styles from "../styles/Home.module.css";
import { useAppContext } from "../context/AppContext";

export default function Home() {
  const { user, setUser } = useAppContext();
  return (
    <div>
      <Head>
        <title>AO Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? <Selector data={data.selector} /> : <MainAuth data={data} />}
    </div>
  );
}
