import Head from "next/head";
import data from "../data/staticData.json"
import MainLogin from "../components/sections/mainLogin/mainLogin";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AO Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MainLogin data={data} />
      </main>
    </div>
  );
}
